version: '3.5'

services:

  mon1:
    build: .
    ports:
      - 6789:6789
    environment:
      - LOG_LEVEL=10

  mon2:
    build: .
    environment:
      - LOG_LEVEL=10
      - PEER_MONITOR_HOST=mon1

  mon3:
    build: .
    environment:
      - LOG_LEVEL=10
      - PEER_MONITOR_HOST=mon2

