version: '3.5'

services:

  etcd0:
    image: quay.io/coreos/etcd
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd0:2379

  mon1:
    build: .
    environment:
      - CREATE_CLUSTER=true
      - ETCD_URL=http://etcd0:2379

  mon2:
    build: .
    environment:
      - PEER_MONITOR_HOSTS=mon1
      - ETCD_URL=http://etcd0:2379

  mon3:
    build: .
    environment:
      - PEER_MONITOR_HOSTS=mon1
      - ETCD_URL=http://etcd0:2379

